### PR TITLE
Add reverse_bits function for 32-bit element packs

### PR DESCRIPTION
**Pull request by Twinklebear**
This PR adds a byteswap function for vectors with 32bit elements. I also removed some use of the AVX512VL instruction set, as this runs into some compilation errors when I was testing it on the Stampede2 skylakes (the mask does not convert to the bool types for 4/8 element vectors).

A remaining todo is byteswap for vectors with 64bit elements.

### CODE REVIEW

**Comment by jeffamstutz** [comment]
Thanks for implementing Will! Before merging, I'd like to propose the following updates:

- W == 1 implementation should operate on ```pack<T, 1>```, not built-in types
- If I understand the implementation correctly, there should only need to be a single implementation of ```byteswap```, as everything has to be ```reinterpret_cast<>``` regardless of input ```T```
- SFINAE (i.e. ```enable_if<>``` usage) is preferred to be at the end of the template argument list instead of in the function declaration. This is for both readability and consistency with SFINAE techniques elsewhere. I think adding a type trait ```is_n_bytes<T, N>``` (and accompanying  ```is_n_bytes_t``` using ```traits::enable_if_t```) would be ideal.
- Place tests in the ```memory``` group instead of its own
- Rename ```byteswap``` to ```reverse_bits```

**Comment by Twinklebear** [comment]
Sounds good! I'll add these changes

**Comment by Twinklebear** [comment]
Let me know how these look, I didn't know about the anonymous template arg style with the default for SFINAE, it's a lot easier to read.

**Comment by Twinklebear** [comment]
Hm, it actually seems now the test is not being run. One second

**Comment by jeffamstutz** [comment]
This looks great, thanks for revising!

**Pull request merged**
